apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: climate-gui
  name: climate-gui
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  selector:
    app: climate-gui
  ports:
    - port: 3000
status:
  loadBalancer: {}
